config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  resources :users
  resources :authentications
  root to: "authentications#new"
  delete '/logout' => 'authentications#destroy'
  get '/logout' => 'authentications#destroy'
end

app/models/alert.rb
class Alert < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password,
            length: { minimum: 6 },
            if: -> { new_record? || !password.nil? }
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: %i[ show edit update destroy ]
  before_action :authorize_request
  
  def index
    @alerts = Alert.all
    respond_to do |format|
        format.html { render :index, :layout => false  }
        format.json { render @alerts, status: :created }
    end
  end

  def show
  end

  def new
    @alert = Alert.new
  end

  def edit
  end

  def create
    @alert = Alert.new(alert_params)
    if alert_params[:alert_type] == 'portal_opened' || alert_params[:alert_type] == 'portal_closed'
      if @alert.save
        render json: @alert, status: :created
      else
        render json: { errors: @alert.errors}, status: :unprocessable_entity
      end
    else
      render json: { errors: "Type should be portal_opened or portal_closed"}, status: :unprocessable_entity
    end
  end

  def update
    if @alert.update(alert_params)
      render json: @alert, status: :ok
    else
      render json: { errors: @alert.errors}, status: :unprocessable_entity
    end
  end

  def destroy
    @alert.destroy
    render json: @alert, status: :ok
  end

  private
    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(:alert_type, :description, :origin , tags:[])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def not_found
    render json: { error: 'not_found' }
  end

  def authorize_request
    header = session[:token] if session[:token].present?
    header = request.headers['token'] if request.headers['token'].present?
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def new
  @user = User.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user&.authenticate(params[:password])
      token = JsonWebToken.encode(user_id: @user.id)
      session[:token] = token
      time = Time.now + 24.hours.to_i
        respond_to do |format|
          if @user.save
              format.html { redirect_to alerts_path  }
              format.json {  render json: { token: token, exp: time.strftime("%m-%d-%Y %H:%M"),
                     user: @user }}
          end
        end
    else
      render json: { error: 'unauthorized' }, status: :unauthorized
    end
  end

  def destroy    
    session[:token] = nil         
    respond_to do |format|
      format.html { render :new }
      format.json {  render :json => "Delete" }
    end 
  end 

  private

  def login_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_request, except: :create
  # before_action :find_user, except: %i[create index]
  skip_before_action :verify_authenticity_token, only: [:create, :new]

  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    render json: @user, status: :ok
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
          format.html { redirect_to alerts_path  }
          format.json {  render :json => @user }
      else
          format.html { render :new }
          format.json {  render :json => "Somthing Wrong" }
      end
    end
  end

  def update
    unless @user.update(user_params)
      render json: { errors: @user.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
  end

  private

  def find_user
    @user = User.find_by_username!(params[:_username])
    rescue ActiveRecord::RecordNotFound
      render json: { errors: 'User not found' }, status: :not_found
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation
    )
  end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alerts/_alert.html.erb
<div id="<%= dom_id alert %>">
  <p>
    <strong>Alert type:</strong>
    <%= alert.alert_type %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= alert.description %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= alert.tags %>
  </p>

  <p>
    <strong>Origin:</strong>
    <%= alert.origin %>
  </p>

</div>

app/views/alerts/_form.html.erb
<%= form_with(model: alert) do |form| %>
  <% if alert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% alert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :alert_type, style: "display: block" %>
    <%= form.text_field :alert_type %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :tags, style: "display: block" %>
    <%= form.text_field :tags %>
  </div>

  <div>
    <%= form.label :origin, style: "display: block" %>
    <%= form.text_field :origin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render "form", alert: @alert %>

<br>

<div>
  <%= link_to "Show this alert", @alert %> |
  <%= link_to "Back to alerts", alerts_path %>
</div>

app/views/alerts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alerts</h1>

<div id="alerts">
  <% @alerts.each do |alert| %>
    <%= render alert %>
    <p>
      <% --------------------------------------------- %>
    </p>
  <% end %>
</div>

<%= link_to "Log out", logout_path, method: "delete" %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render "form", alert: @alert %>

<br>

<div>
  <%= link_to "Back to alerts", alerts_path %>
</div>

app/views/alerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @alert %>

<div>
  <%= link_to "Edit this alert", edit_alert_path(@alert) %> |
  <%= link_to "Back to alerts", alerts_path %>

  <%= button_to "Destroy this alert", @alert, method: :delete %>
</div>

app/views/authentications/new.html.erb
<%= form_with url: authentications_path, method: :post do |form| %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "SignUp", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlertProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with(model: @user) do |form| %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%#= link_to "SignUp", new_user_path %>
<%= link_to "SingIn", authentications_path %>